version: '3'
services:
  magbot:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./src:/ws/src
    network_mode: host
    privileged: true  # Required for hardware access and Gazebo
    devices:
      - /dev/input:/dev/input  # For joystick access
    command: >
      ros2 launch magbot magbot_service.launch.py
      is_sim:=1
      is_physical:=0
      use_joystick:=0
      use_keyboard:=1
      use_imu:=0

  gazebo:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    network_mode: host
    privileged: true
    command: ros2 launch magbot_gazebo rsp.launch.py